//! Autogenerated weights for `pallet_dao`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-03, STEPS: `25`, REPEAT: `100`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `artemlaptop`, CPU: `AMD Ryzen 7 5700U with Radeon Graphics`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// target/release/parachain-template-node
// benchmark
// pallet
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_dao
// --extrinsic
// *
// --steps
// 25
// --repeat
// 100
// --json-file=/home/user/4ire/decentro-blockchain/pallets/dao/src/benchmark_raw.json
// --output
// /home/user/4ire/decentro-blockchain/pallets/dao/src/weights_new.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

pub trait WeightInfo {
	fn add_member() -> Weight;
	fn remove_member() -> Weight;
	fn request_insurance() -> Weight;
	fn vote() -> Weight;
	fn allocate_liquidity() -> Weight;
	fn do_execute_voting_ended() -> Weight;
}

/// Weight functions for `pallet_dao`.
pub struct DaoWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for DaoWeight<T> {
	/// Storage: Collective Members (r:1 w:1)
	/// Proof Skipped: Collective Members (max_values: Some(1), max_size: None, mode: Measured)
	fn add_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `101`
		//  Estimated: `1586`
		// Minimum execution time: 28_022_000 picoseconds.
		Weight::from_parts(29_044_000, 0)
			.saturating_add(Weight::from_parts(0, 1586))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: Collective Members (r:1 w:1)
	/// Proof Skipped: Collective Members (max_values: Some(1), max_size: None, mode: Measured)
	fn remove_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `134`
		//  Estimated: `1619`
		// Minimum execution time: 28_303_000 picoseconds.
		Weight::from_parts(29_034_000, 0)
			.saturating_add(Weight::from_parts(0, 1619))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: Dao NextProposalIndex (r:1 w:1)
	/// Proof Skipped: Dao NextProposalIndex (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:2 w:1)
	/// Proof: Assets Account (max_values: None, max_size: Some(102), added: 2577, mode: MaxEncodedLen)
	/// Storage: Dao PalletAccountId (r:1 w:0)
	/// Proof Skipped: Dao PalletAccountId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Collective ProposalOf (r:1 w:1)
	/// Proof Skipped: Collective ProposalOf (max_values: None, max_size: None, mode: Measured)
	/// Storage: Collective Proposals (r:1 w:1)
	/// Proof Skipped: Collective Proposals (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Collective ProposalCount (r:1 w:1)
	/// Proof Skipped: Collective ProposalCount (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Dao PendingProposalInfo (r:1 w:1)
	/// Proof Skipped: Dao PendingProposalInfo (max_values: None, max_size: None, mode: Measured)
	/// Storage: Dao ActiveVotingMetadata (r:0 w:1)
	/// Proof Skipped: Dao ActiveVotingMetadata (max_values: None, max_size: None, mode: Measured)
	/// Storage: Collective Voting (r:0 w:1)
	/// Proof Skipped: Collective Voting (max_values: None, max_size: None, mode: Measured)
	fn request_insurance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `607`
		//  Estimated: `6144`
		// Minimum execution time: 134_070_000 picoseconds.
		Weight::from_parts(141_814_000, 0)
			.saturating_add(Weight::from_parts(0, 6144))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: Collective Members (r:1 w:0)
	/// Proof Skipped: Collective Members (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Collective Voting (r:1 w:1)
	/// Proof Skipped: Collective Voting (max_values: None, max_size: None, mode: Measured)
	fn vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `292`
		//  Estimated: `3757`
		// Minimum execution time: 41_057_000 picoseconds.
		Weight::from_parts(47_829_000, 0)
			.saturating_add(Weight::from_parts(0, 3757))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: Dao PalletAccountId (r:1 w:0)
	/// Proof Skipped: Dao PalletAccountId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Dao PendingProposalInfo (r:1 w:1)
	/// Proof Skipped: Dao PendingProposalInfo (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets Asset (r:1 w:0)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:1 w:0)
	/// Proof: Assets Account (max_values: None, max_size: Some(102), added: 2577, mode: MaxEncodedLen)
	/// Storage: Uniques Account (r:1 w:1)
	/// Proof: Uniques Account (max_values: None, max_size: Some(88), added: 2563, mode: MaxEncodedLen)
	/// Storage: Insurance NextCollectionId (r:1 w:1)
	/// Proof: Insurance NextCollectionId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Insurance ZeroAddress (r:1 w:0)
	/// Proof: Insurance ZeroAddress (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Uniques Class (r:1 w:1)
	/// Proof: Uniques Class (max_values: None, max_size: Some(178), added: 2653, mode: MaxEncodedLen)
	/// Storage: Uniques Asset (r:1 w:1)
	/// Proof: Uniques Asset (max_values: None, max_size: Some(122), added: 2597, mode: MaxEncodedLen)
	/// Storage: Uniques CollectionMaxSupply (r:1 w:0)
	/// Proof: Uniques CollectionMaxSupply (max_values: None, max_size: Some(24), added: 2499, mode: MaxEncodedLen)
	/// Storage: Collective Members (r:1 w:0)
	/// Proof Skipped: Collective Members (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Uniques ClassAccount (r:0 w:1)
	/// Proof: Uniques ClassAccount (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// Storage: Dao ShouldUnreserveFunds (r:0 w:1)
	/// Proof Skipped: Dao ShouldUnreserveFunds (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Dao DaoMembersForInsurance (r:0 w:1)
	/// Proof Skipped: Dao DaoMembersForInsurance (max_values: None, max_size: None, mode: Measured)
	/// Storage: Insurance Metadata (r:0 w:1)
	/// Proof: Insurance Metadata (max_values: None, max_size: Some(171), added: 2646, mode: MaxEncodedLen)
	/// Storage: Insurance NextItemIdForCollection (r:0 w:1)
	/// Proof: Insurance NextItemIdForCollection (max_values: None, max_size: Some(24), added: 2499, mode: MaxEncodedLen)
	fn allocate_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1062`
		//  Estimated: `4527`
		// Minimum execution time: 142_897_000 picoseconds.
		Weight::from_parts(173_724_000, 0)
			.saturating_add(Weight::from_parts(0, 4527))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: Dao ActiveVotingMetadata (r:2 w:1)
	/// Proof Skipped: Dao ActiveVotingMetadata (max_values: None, max_size: None, mode: Measured)
	/// Storage: Collective Voting (r:1 w:1)
	/// Proof Skipped: Collective Voting (max_values: None, max_size: None, mode: Measured)
	/// Storage: Collective Members (r:1 w:0)
	/// Proof Skipped: Collective Members (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Collective ProposalOf (r:1 w:1)
	/// Proof Skipped: Collective ProposalOf (max_values: None, max_size: None, mode: Measured)
	/// Storage: Collective Proposals (r:1 w:1)
	/// Proof Skipped: Collective Proposals (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:1 w:1)
	/// Proof: Assets Account (max_values: None, max_size: Some(102), added: 2577, mode: MaxEncodedLen)
	/// Storage: Dao ShouldUnreserveFunds (r:0 w:1)
	/// Proof Skipped: Dao ShouldUnreserveFunds (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Dao PendingProposalInfo (r:0 w:1)
	/// Proof Skipped: Dao PendingProposalInfo (max_values: None, max_size: None, mode: Measured)
	fn do_execute_voting_ended() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1112`
		//  Estimated: `7052`
		// Minimum execution time: 112_951_000 picoseconds.
		Weight::from_parts(130_253_000, 0)
			.saturating_add(Weight::from_parts(0, 7052))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(8))
	}
}

impl WeightInfo for () {
	/// Storage: Collective Members (r:1 w:1)
	/// Proof Skipped: Collective Members (max_values: Some(1), max_size: None, mode: Measured)
	fn add_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `101`
		//  Estimated: `1586`
		// Minimum execution time: 28_022_000 picoseconds.
		Weight::from_parts(29_044_000, 0)
			.saturating_add(Weight::from_parts(0, 1586))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: Collective Members (r:1 w:1)
	/// Proof Skipped: Collective Members (max_values: Some(1), max_size: None, mode: Measured)
	fn remove_member() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `134`
		//  Estimated: `1619`
		// Minimum execution time: 28_303_000 picoseconds.
		Weight::from_parts(29_034_000, 0)
			.saturating_add(Weight::from_parts(0, 1619))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: Dao NextProposalIndex (r:1 w:1)
	/// Proof Skipped: Dao NextProposalIndex (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:2 w:1)
	/// Proof: Assets Account (max_values: None, max_size: Some(102), added: 2577, mode: MaxEncodedLen)
	/// Storage: Dao PalletAccountId (r:1 w:0)
	/// Proof Skipped: Dao PalletAccountId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Collective ProposalOf (r:1 w:1)
	/// Proof Skipped: Collective ProposalOf (max_values: None, max_size: None, mode: Measured)
	/// Storage: Collective Proposals (r:1 w:1)
	/// Proof Skipped: Collective Proposals (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Collective ProposalCount (r:1 w:1)
	/// Proof Skipped: Collective ProposalCount (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Dao PendingProposalInfo (r:1 w:1)
	/// Proof Skipped: Dao PendingProposalInfo (max_values: None, max_size: None, mode: Measured)
	/// Storage: Dao ActiveVotingMetadata (r:0 w:1)
	/// Proof Skipped: Dao ActiveVotingMetadata (max_values: None, max_size: None, mode: Measured)
	/// Storage: Collective Voting (r:0 w:1)
	/// Proof Skipped: Collective Voting (max_values: None, max_size: None, mode: Measured)
	fn request_insurance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `607`
		//  Estimated: `6144`
		// Minimum execution time: 134_070_000 picoseconds.
		Weight::from_parts(141_814_000, 0)
			.saturating_add(Weight::from_parts(0, 6144))
			.saturating_add(RocksDbWeight::get().reads(9))
			.saturating_add(RocksDbWeight::get().writes(9))
	}
	/// Storage: Collective Members (r:1 w:0)
	/// Proof Skipped: Collective Members (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Collective Voting (r:1 w:1)
	/// Proof Skipped: Collective Voting (max_values: None, max_size: None, mode: Measured)
	fn vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `292`
		//  Estimated: `3757`
		// Minimum execution time: 41_057_000 picoseconds.
		Weight::from_parts(47_829_000, 0)
			.saturating_add(Weight::from_parts(0, 3757))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: Dao PalletAccountId (r:1 w:0)
	/// Proof Skipped: Dao PalletAccountId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Dao PendingProposalInfo (r:1 w:1)
	/// Proof Skipped: Dao PendingProposalInfo (max_values: None, max_size: None, mode: Measured)
	/// Storage: Assets Asset (r:1 w:0)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:1 w:0)
	/// Proof: Assets Account (max_values: None, max_size: Some(102), added: 2577, mode: MaxEncodedLen)
	/// Storage: Uniques Account (r:1 w:1)
	/// Proof: Uniques Account (max_values: None, max_size: Some(88), added: 2563, mode: MaxEncodedLen)
	/// Storage: Insurance NextCollectionId (r:1 w:1)
	/// Proof: Insurance NextCollectionId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Insurance ZeroAddress (r:1 w:0)
	/// Proof: Insurance ZeroAddress (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Uniques Class (r:1 w:1)
	/// Proof: Uniques Class (max_values: None, max_size: Some(178), added: 2653, mode: MaxEncodedLen)
	/// Storage: Uniques Asset (r:1 w:1)
	/// Proof: Uniques Asset (max_values: None, max_size: Some(122), added: 2597, mode: MaxEncodedLen)
	/// Storage: Uniques CollectionMaxSupply (r:1 w:0)
	/// Proof: Uniques CollectionMaxSupply (max_values: None, max_size: Some(24), added: 2499, mode: MaxEncodedLen)
	/// Storage: Collective Members (r:1 w:0)
	/// Proof Skipped: Collective Members (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Uniques ClassAccount (r:0 w:1)
	/// Proof: Uniques ClassAccount (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// Storage: Dao ShouldUnreserveFunds (r:0 w:1)
	/// Proof Skipped: Dao ShouldUnreserveFunds (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Dao DaoMembersForInsurance (r:0 w:1)
	/// Proof Skipped: Dao DaoMembersForInsurance (max_values: None, max_size: None, mode: Measured)
	/// Storage: Insurance Metadata (r:0 w:1)
	/// Proof: Insurance Metadata (max_values: None, max_size: Some(171), added: 2646, mode: MaxEncodedLen)
	/// Storage: Insurance NextItemIdForCollection (r:0 w:1)
	/// Proof: Insurance NextItemIdForCollection (max_values: None, max_size: Some(24), added: 2499, mode: MaxEncodedLen)
	fn allocate_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1062`
		//  Estimated: `4527`
		// Minimum execution time: 142_897_000 picoseconds.
		Weight::from_parts(173_724_000, 0)
			.saturating_add(Weight::from_parts(0, 4527))
			.saturating_add(RocksDbWeight::get().reads(11))
			.saturating_add(RocksDbWeight::get().writes(10))
	}
	/// Storage: Dao ActiveVotingMetadata (r:2 w:1)
	/// Proof Skipped: Dao ActiveVotingMetadata (max_values: None, max_size: None, mode: Measured)
	/// Storage: Collective Voting (r:1 w:1)
	/// Proof Skipped: Collective Voting (max_values: None, max_size: None, mode: Measured)
	/// Storage: Collective Members (r:1 w:0)
	/// Proof Skipped: Collective Members (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Collective ProposalOf (r:1 w:1)
	/// Proof Skipped: Collective ProposalOf (max_values: None, max_size: None, mode: Measured)
	/// Storage: Collective Proposals (r:1 w:1)
	/// Proof Skipped: Collective Proposals (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:1 w:1)
	/// Proof: Assets Account (max_values: None, max_size: Some(102), added: 2577, mode: MaxEncodedLen)
	/// Storage: Dao ShouldUnreserveFunds (r:0 w:1)
	/// Proof Skipped: Dao ShouldUnreserveFunds (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Dao PendingProposalInfo (r:0 w:1)
	/// Proof Skipped: Dao PendingProposalInfo (max_values: None, max_size: None, mode: Measured)
	fn do_execute_voting_ended() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1112`
		//  Estimated: `7052`
		// Minimum execution time: 112_951_000 picoseconds.
		Weight::from_parts(130_253_000, 0)
			.saturating_add(Weight::from_parts(0, 7052))
			.saturating_add(RocksDbWeight::get().reads(8))
			.saturating_add(RocksDbWeight::get().writes(8))
	}
}
