//! Autogenerated weights for `pallet_marketplace`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-05, STEPS: `25`, REPEAT: `100`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `artemlaptop`, CPU: `AMD Ryzen 7 5700U with Radeon Graphics`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// target/release/parachain-template-node
// benchmark
// pallet
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_marketplace
// --extrinsic
// *
// --steps
// 25
// --repeat
// 100
// --json-file=/home/user/4ire/decentro-blockchain/pallets/marketplace/src/benchmark_raw.json
// --output
// /home/user/4ire/decentro-blockchain/pallets/marketplace/src/weights_new.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

pub trait WeightInfo {
	fn provide_liquidity() -> Weight;
	fn create_order_buy() -> Weight;
	fn create_order_sell() -> Weight;
	fn cancel_order_buy() -> Weight;
	fn cancel_order_sell() -> Weight;
	fn fulfill_order_buy() -> Weight;
	fn fulfill_order_sell() -> Weight;
}

/// Weight functions for `pallet_marketplace`.
pub struct MarketplaceWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for MarketplaceWeight<T> {
	/// Storage: Dao PalletAccountId (r:1 w:0)
	/// Proof Skipped: Dao PalletAccountId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Insurance Metadata (r:1 w:1)
	/// Proof: Insurance Metadata (max_values: None, max_size: Some(171), added: 2646, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:2 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:1 w:0)
	/// Proof: Assets Account (max_values: None, max_size: Some(102), added: 2577, mode: MaxEncodedLen)
	/// Storage: Insurance NextSmtId (r:1 w:1)
	/// Proof: Insurance NextSmtId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Insurance ZeroAddress (r:1 w:0)
	/// Proof: Insurance ZeroAddress (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Insurance SmtIdToInsurance (r:0 w:1)
	/// Proof: Insurance SmtIdToInsurance (max_values: None, max_size: Some(28), added: 2503, mode: MaxEncodedLen)
	fn provide_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `843`
		//  Estimated: `6360`
		// Minimum execution time: 85_854_000 picoseconds.
		Weight::from_parts(108_753_000, 0)
			.saturating_add(Weight::from_parts(0, 6360))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: Marketplace NextOrderId (r:1 w:1)
	/// Proof: Marketplace NextOrderId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:1 w:1)
	/// Proof: Assets Account (max_values: None, max_size: Some(102), added: 2577, mode: MaxEncodedLen)
	/// Storage: Marketplace OrderBook (r:0 w:1)
	/// Proof: Marketplace OrderBook (max_values: None, max_size: Some(93), added: 2568, mode: MaxEncodedLen)
	fn create_order_buy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `544`
		//  Estimated: `3675`
		// Minimum execution time: 52_462_000 picoseconds.
		Weight::from_parts(59_296_000, 0)
			.saturating_add(Weight::from_parts(0, 3675))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: Marketplace NextOrderId (r:1 w:1)
	/// Proof: Marketplace NextOrderId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Marketplace PalletAccountId (r:1 w:0)
	/// Proof: Marketplace PalletAccountId (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:2 w:2)
	/// Proof: Assets Account (max_values: None, max_size: Some(102), added: 2577, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Marketplace OrderBook (r:0 w:1)
	/// Proof: Marketplace OrderBook (max_values: None, max_size: Some(93), added: 2568, mode: MaxEncodedLen)
	fn create_order_sell() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `524`
		//  Estimated: `6144`
		// Minimum execution time: 93_169_000 picoseconds.
		Weight::from_parts(104_433_000, 0)
			.saturating_add(Weight::from_parts(0, 6144))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: Marketplace OrderBook (r:1 w:1)
	/// Proof: Marketplace OrderBook (max_values: None, max_size: Some(93), added: 2568, mode: MaxEncodedLen)
	/// Storage: Marketplace OrderSMTsAmount (r:1 w:1)
	/// Proof: Marketplace OrderSMTsAmount (max_values: None, max_size: Some(24602), added: 27077, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:1 w:1)
	/// Proof: Assets Account (max_values: None, max_size: Some(102), added: 2577, mode: MaxEncodedLen)
	fn cancel_order_buy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `619`
		//  Estimated: `28067`
		// Minimum execution time: 50_578_000 picoseconds.
		Weight::from_parts(61_010_000, 0)
			.saturating_add(Weight::from_parts(0, 28067))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: Marketplace OrderBook (r:1 w:1)
	/// Proof: Marketplace OrderBook (max_values: None, max_size: Some(93), added: 2568, mode: MaxEncodedLen)
	/// Storage: Marketplace OrderSMTsAmount (r:1 w:1)
	/// Proof: Marketplace OrderSMTsAmount (max_values: None, max_size: Some(24602), added: 27077, mode: MaxEncodedLen)
	/// Storage: Marketplace PalletAccountId (r:1 w:0)
	/// Proof: Marketplace PalletAccountId (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:2 w:2)
	/// Proof: Assets Account (max_values: None, max_size: Some(102), added: 2577, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn cancel_order_sell() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `852`
		//  Estimated: `28067`
		// Minimum execution time: 110_937_000 picoseconds.
		Weight::from_parts(130_950_000, 0)
			.saturating_add(Weight::from_parts(0, 28067))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: Marketplace OrderBook (r:1 w:0)
	/// Proof: Marketplace OrderBook (max_values: None, max_size: Some(93), added: 2568, mode: MaxEncodedLen)
	/// Storage: Marketplace OrderSMTsAmount (r:1 w:1)
	/// Proof: Marketplace OrderSMTsAmount (max_values: None, max_size: Some(24602), added: 27077, mode: MaxEncodedLen)
	/// Storage: Marketplace PalletAccountId (r:1 w:0)
	/// Proof: Marketplace PalletAccountId (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:2 w:2)
	/// Proof: Assets Account (max_values: None, max_size: Some(102), added: 2577, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn fulfill_order_buy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `672`
		//  Estimated: `28067`
		// Minimum execution time: 100_945_000 picoseconds.
		Weight::from_parts(113_763_000, 0)
			.saturating_add(Weight::from_parts(0, 28067))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: Marketplace OrderBook (r:1 w:0)
	/// Proof: Marketplace OrderBook (max_values: None, max_size: Some(93), added: 2568, mode: MaxEncodedLen)
	/// Storage: Marketplace OrderSMTsAmount (r:1 w:1)
	/// Proof: Marketplace OrderSMTsAmount (max_values: None, max_size: Some(24602), added: 27077, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:1 w:1)
	/// Proof: Assets Account (max_values: None, max_size: Some(102), added: 2577, mode: MaxEncodedLen)
	fn fulfill_order_sell() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `726`
		//  Estimated: `28067`
		// Minimum execution time: 62_273_000 picoseconds.
		Weight::from_parts(69_097_000, 0)
			.saturating_add(Weight::from_parts(0, 28067))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}

impl WeightInfo for () {
	/// Storage: Dao PalletAccountId (r:1 w:0)
	/// Proof Skipped: Dao PalletAccountId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Insurance Metadata (r:1 w:1)
	/// Proof: Insurance Metadata (max_values: None, max_size: Some(171), added: 2646, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:2 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:1 w:0)
	/// Proof: Assets Account (max_values: None, max_size: Some(102), added: 2577, mode: MaxEncodedLen)
	/// Storage: Insurance NextSmtId (r:1 w:1)
	/// Proof: Insurance NextSmtId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Insurance ZeroAddress (r:1 w:0)
	/// Proof: Insurance ZeroAddress (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Insurance SmtIdToInsurance (r:0 w:1)
	/// Proof: Insurance SmtIdToInsurance (max_values: None, max_size: Some(28), added: 2503, mode: MaxEncodedLen)
	fn provide_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `843`
		//  Estimated: `6360`
		// Minimum execution time: 85_854_000 picoseconds.
		Weight::from_parts(108_753_000, 0)
			.saturating_add(Weight::from_parts(0, 6360))
			.saturating_add(RocksDbWeight::get().reads(7))
			.saturating_add(RocksDbWeight::get().writes(4))
	}
	/// Storage: Marketplace NextOrderId (r:1 w:1)
	/// Proof: Marketplace NextOrderId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:1 w:1)
	/// Proof: Assets Account (max_values: None, max_size: Some(102), added: 2577, mode: MaxEncodedLen)
	/// Storage: Marketplace OrderBook (r:0 w:1)
	/// Proof: Marketplace OrderBook (max_values: None, max_size: Some(93), added: 2568, mode: MaxEncodedLen)
	fn create_order_buy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `544`
		//  Estimated: `3675`
		// Minimum execution time: 52_462_000 picoseconds.
		Weight::from_parts(59_296_000, 0)
			.saturating_add(Weight::from_parts(0, 3675))
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(4))
	}
	/// Storage: Marketplace NextOrderId (r:1 w:1)
	/// Proof: Marketplace NextOrderId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Marketplace PalletAccountId (r:1 w:0)
	/// Proof: Marketplace PalletAccountId (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:2 w:2)
	/// Proof: Assets Account (max_values: None, max_size: Some(102), added: 2577, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Marketplace OrderBook (r:0 w:1)
	/// Proof: Marketplace OrderBook (max_values: None, max_size: Some(93), added: 2568, mode: MaxEncodedLen)
	fn create_order_sell() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `524`
		//  Estimated: `6144`
		// Minimum execution time: 93_169_000 picoseconds.
		Weight::from_parts(104_433_000, 0)
			.saturating_add(Weight::from_parts(0, 6144))
			.saturating_add(RocksDbWeight::get().reads(6))
			.saturating_add(RocksDbWeight::get().writes(6))
	}
	/// Storage: Marketplace OrderBook (r:1 w:1)
	/// Proof: Marketplace OrderBook (max_values: None, max_size: Some(93), added: 2568, mode: MaxEncodedLen)
	/// Storage: Marketplace OrderSMTsAmount (r:1 w:1)
	/// Proof: Marketplace OrderSMTsAmount (max_values: None, max_size: Some(24602), added: 27077, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:1 w:1)
	/// Proof: Assets Account (max_values: None, max_size: Some(102), added: 2577, mode: MaxEncodedLen)
	fn cancel_order_buy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `619`
		//  Estimated: `28067`
		// Minimum execution time: 50_578_000 picoseconds.
		Weight::from_parts(61_010_000, 0)
			.saturating_add(Weight::from_parts(0, 28067))
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(4))
	}
	/// Storage: Marketplace OrderBook (r:1 w:1)
	/// Proof: Marketplace OrderBook (max_values: None, max_size: Some(93), added: 2568, mode: MaxEncodedLen)
	/// Storage: Marketplace OrderSMTsAmount (r:1 w:1)
	/// Proof: Marketplace OrderSMTsAmount (max_values: None, max_size: Some(24602), added: 27077, mode: MaxEncodedLen)
	/// Storage: Marketplace PalletAccountId (r:1 w:0)
	/// Proof: Marketplace PalletAccountId (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:2 w:2)
	/// Proof: Assets Account (max_values: None, max_size: Some(102), added: 2577, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn cancel_order_sell() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `852`
		//  Estimated: `28067`
		// Minimum execution time: 110_937_000 picoseconds.
		Weight::from_parts(130_950_000, 0)
			.saturating_add(Weight::from_parts(0, 28067))
			.saturating_add(RocksDbWeight::get().reads(7))
			.saturating_add(RocksDbWeight::get().writes(6))
	}
	/// Storage: Marketplace OrderBook (r:1 w:0)
	/// Proof: Marketplace OrderBook (max_values: None, max_size: Some(93), added: 2568, mode: MaxEncodedLen)
	/// Storage: Marketplace OrderSMTsAmount (r:1 w:1)
	/// Proof: Marketplace OrderSMTsAmount (max_values: None, max_size: Some(24602), added: 27077, mode: MaxEncodedLen)
	/// Storage: Marketplace PalletAccountId (r:1 w:0)
	/// Proof: Marketplace PalletAccountId (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:2 w:2)
	/// Proof: Assets Account (max_values: None, max_size: Some(102), added: 2577, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn fulfill_order_buy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `672`
		//  Estimated: `28067`
		// Minimum execution time: 100_945_000 picoseconds.
		Weight::from_parts(113_763_000, 0)
			.saturating_add(Weight::from_parts(0, 28067))
			.saturating_add(RocksDbWeight::get().reads(7))
			.saturating_add(RocksDbWeight::get().writes(5))
	}
	/// Storage: Marketplace OrderBook (r:1 w:0)
	/// Proof: Marketplace OrderBook (max_values: None, max_size: Some(93), added: 2568, mode: MaxEncodedLen)
	/// Storage: Marketplace OrderSMTsAmount (r:1 w:1)
	/// Proof: Marketplace OrderSMTsAmount (max_values: None, max_size: Some(24602), added: 27077, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:1 w:1)
	/// Proof: Assets Account (max_values: None, max_size: Some(102), added: 2577, mode: MaxEncodedLen)
	fn fulfill_order_sell() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `726`
		//  Estimated: `28067`
		// Minimum execution time: 62_273_000 picoseconds.
		Weight::from_parts(69_097_000, 0)
			.saturating_add(Weight::from_parts(0, 28067))
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
}
