//! Autogenerated weights for `pallet_payout_processor`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-05, STEPS: `25`, REPEAT: `100`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `artemlaptop`, CPU: `AMD Ryzen 7 5700U with Radeon Graphics`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use frame_support::weights::constants::RocksDbWeight;
use core::marker::PhantomData;

/// Weight functions for `pallet_payout_processor`.
pub trait WeightInfo {
	fn set_insurance_count() -> Weight;
	fn set_event_threshold() -> Weight;
	fn set_location_coordinates() -> Weight;
	fn set_location_name() -> Weight;
	fn on_initialize() -> Weight;
}

/// Weight functions for `pallet_payout_processor`.
pub struct PayoutProcessorWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for PayoutProcessorWeight<T> {
	/// Storage: PayoutProcessor InsuranceCount (r:0 w:1)
	/// Proof: PayoutProcessor InsuranceCount (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	fn set_insurance_count() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `503`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 503))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: PayoutProcessor EventThresholds (r:0 w:1)
	/// Proof: PayoutProcessor EventThresholds (max_values: None, max_size: Some(12), added: 2487, mode: MaxEncodedLen)
	fn set_event_threshold() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `2487`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(15_000_000, 0)
			.saturating_add(Weight::from_parts(0, 2487))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: PayoutProcessor LocationCoordinates (r:0 w:1)
	/// Proof: PayoutProcessor LocationCoordinates (max_values: None, max_size: Some(12), added: 2487, mode: MaxEncodedLen)
	fn set_location_coordinates() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `2487`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(15_000_000, 0)
			.saturating_add(Weight::from_parts(0, 2487))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: PayoutProcessor LocationNames (r:0 w:1)
	/// Proof: PayoutProcessor LocationNames (max_values: None, max_size: Some(76), added: 2551, mode: MaxEncodedLen)
	fn set_location_name() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `2551`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(20_000_000, 0)
			.saturating_add(Weight::from_parts(0, 2551))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn on_initialize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 1_000_000 picoseconds.
		Weight::from_parts(1_000_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
}

