//! Autogenerated weights for `pallet_insurances`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-05, STEPS: `25`, REPEAT: `100`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `artemlaptop`, CPU: `AMD Ryzen 7 5700U with Radeon Graphics`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use frame_support::weights::constants::RocksDbWeight;
use core::marker::PhantomData;

/// Weight functions for `pallet_insurances`.
pub trait WeightInfo {
	fn create_insurance() -> Weight;
	fn destroy_insurance() -> Weight;
	fn mint_secondary_market_tokens() -> Weight;
}

/// Weight functions for `pallet_insurances`.
pub struct InsurancesWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for InsurancesWeight<T> {
	/// Storage: Insurances Metadata (r:0 w:1)
	/// Proof: Insurances Metadata (max_values: None, max_size: Some(100), added: 2575, mode: MaxEncodedLen)
	fn create_insurance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `2575`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(20_000_000, 0)
			.saturating_add(Weight::from_parts(0, 2575))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: Insurances Metadata (r:1 w:1)
	/// Proof: Insurances Metadata (max_values: None, max_size: Some(100), added: 2575, mode: MaxEncodedLen)
	fn destroy_insurance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `2575`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(15_000_000, 0)
			.saturating_add(Weight::from_parts(0, 2575))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: Insurances NextSmtId (r:1 w:1)
	/// Proof: Insurances NextSmtId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	fn mint_secondary_market_tokens() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `499`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(25_000_000, 0)
			.saturating_add(Weight::from_parts(0, 499))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
